font: "CaskaydiaMono Nerd Font 18"
border_width: 4
corner_r: 0
padding: 15
rows_per_column: 3
column_padding: 25
anchor: center
margin_top: 0
margin_right: 0
margin_bottom: 0
margin_left: 0
inhibit_compositor_keyboard_shortcuts: true
auto_kbd_layout: true
menu:
  # col:
  # [ q
  #   a
  #   z ]
  - key: "q"
    desc: "osu!lazer"
    cmd: "osu-lazer"

  - key: "a"
    desc: "<blank>"
    cmd: ""

  - key: "z"
    desc: "Obsidian"
    cmd: "obsidian"

  # col:
  # [ w
  #   s
  #   x ]

  - key: "w"
    desc: "AmneziaVPN"
    cmd: "AmneziaVPN"

  - key: "s"
    desc: "Zen"
    cmd: "zen-browser"

  - key: "x"
    desc: "Zathura"
    cmd: "zathura $HOME/obsidian-vault/static/books/"

  # col:
  # [ e
  #   d
  #   c ]

  - key: "e"
    desc: "Anki"
    cmd: "anki"

  - key: "d"
    desc: "Throne"
    cmd: "throne"

  - key: "c"
    desc: "DBX"
    cmd: "dbx"
