### Terminal
set-option -g default-shell /bin/zsh
set -g default-terminal     "tmux-256color"
set -g focus-events         on
set -g allow-passthrough on

### Indexing
set  -g base-index      1
setw -g pane-base-index 1

### Key modes
set -g status-keys emacs
set -g mode-keys   emacs

### Behaviour
set  -g mouse             on
setw -g aggressive-resize on
setw -g clock-mode-style  24
set  -s escape-time       500
set  -g history-limit     2000
set -g mouse              on
set -g base-index         1
setw -g pane-base-index   1
set -sg escape-time       0

### Prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix
bind r source-file ~/.config/tmux/tmux.conf

### Style
set -ga terminal-features 'xterm-256color:RGB'
set -g @tmux_muted "colour244"
set -g @tmux_accent "colour9"
set -g @tmux_accent_text "colour232"
source-file -q ~/.local/state/omarchy/current/theme/tmux.conf

### Status bar
set -g status-position bottom
set -g status-justify  right
set -g status-style    bg=default
set -g status-interval 1

set -g status-left-length  99
set -g status-left-length  99
set -g status-left         ""
set -g status-right-length 99
set -g status-right        ""

set -g window-status-format         " #[fg=#{@tmux_muted}]#I:#W "
set -g window-status-current-format " #[bg=#{@tmux_accent},fg=#{@tmux_accent_text}]#I:#W*#[default] "

### Splits
bind s split-window -h
bind v split-window -v

### Movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

### Rotations
bind < swap-pane -U
bind > swap-pane -D

### Kill
bind z kill-pane
bind x kill-window

### Work with windows
bind c new-window
bind p previous-window
bind n next-window
bind w choose-window

### Work with sessions
bind q choose-session

# Keybinding help
bind ? display-popup -E -w 80% -h 70% -T "Tmux keybindings" "omarchy menu tmux keybindings --print | less -R"

bind -n M-Enter split-window -v -c "#{pane_current_path}"
bind -n M-S-Enter split-window -h -c "#{pane_current_path}"
bind -n M-Escape kill-pane

# Enable OSC 52 clipboard forwarding for remote Neovim yanks.
set -as terminal-features ",*:clipboard"
