# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 0
    gaps_out = 0

    border_size = 4
    # accent color (ashen theme)
    # col.active_border = rgb(d76047)
    col.active_border = rgb(4a5642)
    # col.inactive_border = rgb(7a8478)
    layout = scrolling 
}

scrolling {
    column_width = 0.5
    fullscreen_on_one_column = true
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 0
    shadow {
        enabled = false
    }
    blur {
        enabled = true
    }
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 0 0
    # preserve_split=true
    # pseudotile=true
}

# Disable all animations
animations {
    enabled = false
}


