# Override default opacity - no transparency
workspace = 5, layoutopt:direction:left

windowrule {
  name = override-opacity
  opacity = 1.0 override 1.0 override 
  match:class = .*
}

windowrule {
  name = amneziavpn
  float = on
  center = on
  match:class = (AmneziaVPN)$
}

windowrule {
  name = throne
  float = on
  match:class = (Throne)$
}

windowrule {
  name = file-manager
  float = on
  size = 800 600 
  match:class = (org.gnome.Nautilus)$
}

windowrule {
  name = browsers-ws1
  workspace = 1 silent
  match:class = (zen|Zen|firefox|Firefox|librewolf|LibreWolf|floorp|Mercury|chromium|Chromium|chrome|Chrome|brave|Brave|microsoft-edge|Edge|waterfox|Waterfox|thorium|Thorium)
}

windowrule {
  name = web-devtools
  float = on
  workspace = 1 silent
  match:class = (zen-browser)$
  match:title = (Developer Tools)$
}

windowrule {
  name = work-ws2
  workspace = 2 silent
  match:class = (code|Code|code-oss|Code-OSS|codium|Codium|VSCodium|dev.zed.Zed|Zed|subl|CodeBlocks|codeblocks|jetbrains-idea|IntelliJ|CLion|PyCharm|WebStorm|PhpStorm|rider|datagrip|goland|rustrover|android-studio|Studio)
}


windowrule {
  name = spotify
  float = on
  center = on
  size = 1000 700
  match:class = (Spotify)
}


windowrule {
  name = freesmlauncher
  workspace = 3
  float = on
  size = 1000 700
  match:class = (FreesmLauncher)$
}


windowrule {
  name = social-ws5
  workspace = 5 silent
  match:class = (discord|Discord|Vesktop|telegram|Telegram|AyuGram|ayugram|org.telegram.desktop|WebCord|webcord)
}


windowrule {
  name = sound-control
  float = on
  center = on
  size = 1160 630
  match:class = (org.pulseaudio.pavucontrol)$
}


windowrule {
  name = qt
  float = on
  center = on
  match:class = (qt.*ct)$
}
