#pragma once

#define VIAL_KEYBOARD_UID {0x97, 0xD0, 0xA5, 0x97, 0x57, 0x48, 0xD0, 0x4F}

#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 3

#define TAPPING_TERM 150
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0
