VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

RAW_ENABLE = yes

DYNAMIC_KEYMAP_ENABLE = yes
DYNAMIC_KEYMAP_COMBO_ENABLE = yes
DYNAMIC_KEYMAP_TAP_DANCE_ENABLE = yes
DYNAMIC_KEYMAP_KEY_OVERRIDE_ENABLE = yes
DYNAMIC_KEYMAP_QMK_SETTINGS_ENABLE = yes
DYNAMIC_KEYMAP_ALT_REPEAT_ENABLE = yes

BOOTMAGIC_ENABLE = yes
